#!/bin/tcsh
#
# DL_POLY utility to archive I/O files to the data directory
#
if !(-e ../data/TEST$1) then
  mkdir ../data/TEST$1
endif
if !(-e ../data/TEST$1/$2) then
  mkdir ../data/TEST$1/$2
endif
mv CONTROL ../data/TEST$1/$2/CONTROL
mv FIELD ../data/TEST$1/$2/FIELD
mv CONFIG ../data/TEST$1/$2/CONFIG
mv OUTPUT ../data/TEST$1/$2/OUTPUT
mv REVIVE ../data/TEST$1/$2/REVIVE
mv REVCON ../data/TEST$1/$2/REVCON
if (-e TABLE) then
  mv TABLE ../data/TEST$1/$2/TABLE
endif
if (-e TABEAM) then
  mv TABEAM ../data/TEST$1/$2/TABEAM
endif
if (-e STATIS) then
  mv STATIS ../data/TEST$1/$2/STATIS
endif
if (-e RDFDAT) then
  mv RDFDAT ../data/TEST$1/$2/RDFDAT
endif
if (-e ZDNDAT) then
  mv ZDNDAT ../data/TEST$1/$2/ZDNDAT
endif
if (-e CFGMIN) then
  mv CFGMIN ../data/TEST$1/$2/CFGMIN
endif
